# This is a basic workflow to help you get started with Actions

name: armDeployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  subscriptionId: 43b3f2ee-7c26-4ac9-b907-0fd7ce508380

jobs:
  armDeployStaging:
    name: Deploy to Stagging
    runs-on: ubuntu-latest
    env:
      resource_group_name: rg-stg-armtemplate-github
      location: "Southeast Asia"
    enviornment:
      name: Staging

    steps:
      - uses: actions/checkout@v1

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          region: ${{ env.location }}
          subscriptionId: ${{ env.subscriptionId }}
          template: ./arm-templates/arm-resourcegroup.json
          parameters: 
            location="${{ env.location }}"
            resourceGroupName="${{ env.resource_group_name}}"
          deploymentName: arm-resourcegroup
          deploymentMode: Incremental
          failOnStdErr: true

      - name: Deploy Storage Account to resource group
        uses: Azure/arm-deploy@v1
        id: storageAccountDeploy
        with:
          region: ${{ env.location }}
          resourceGroupName: ${{ env.resource_group_name}}
          subscriptionId: ${{ env.subscriptionId }}
          template: ./arm-templates/storageaccount.json
          parameters: 
            ./arm-templates/storageaccount.parameters.json
            storageAccountName="kasunnewsa"
          deploymentName: arm-storageaccount
          deploymentMode: Incremental
          failOnStdErr: true  
      
      - name: Deploy Virtual Machine to resource group
        uses: Azure/arm-deploy@v1
        with:
          region: ${{ env.location }}
          resourceGroupName: ${{ env.resource_group_name}}
          subscriptionId: ${{ env.subscriptionId }}
          template: ./arm-templates/virtualmachine.json
          parameters:
            adminPassword=${{ secrets.VM_ADMIN_PASSWORD}}
          deploymentName: arm-vmdeploy
          deploymentMode: Incremental
          failOnStdErr: true     
          
  armDeployProduction:
    name: Deploy to Production
    runs-on: ubuntu-latest
    env:
      resource_group_name: rg-prod-armtemplate-github
      location: "Southeast Asia"
    enviornment:
      name: Production
    
      needs: armDeployStaging

    steps:
      - uses: actions/checkout@v1

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          region: ${{ env.location }}
          subscriptionId: ${{ env.subscriptionId }}
          template: ./arm-templates/arm-resourcegroup.json
          parameters: 
            location="${{ env.location }}"
            resourceGroupName="${{ env.resource_group_name}}"
          deploymentName: arm-resourcegroup
          deploymentMode: Incremental
          failOnStdErr: true

      - name: Deploy Storage Account to resource group
        uses: Azure/arm-deploy@v1
        id: storageAccountDeploy
        with:
          region: ${{ env.location }}
          resourceGroupName: ${{ env.resource_group_name}}
          subscriptionId: ${{ env.subscriptionId }}
          template: ./arm-templates/storageaccount.json
          parameters: 
            ./arm-templates/storageaccount.parameters.json
            storageAccountName="kasunnewsaprod"
          deploymentName: arm-storageaccount
          deploymentMode: Incremental
          failOnStdErr: true  
      
      - name: Deploy Virtual Machine to resource group
        uses: Azure/arm-deploy@v1
        with:
          region: ${{ env.location }}
          resourceGroupName: ${{ env.resource_group_name}}
          subscriptionId: ${{ env.subscriptionId }}
          template: ./arm-templates/virtualmachine.json
          parameters:
            adminPassword=${{ secrets.VM_ADMIN_PASSWORD}}
          deploymentName: arm-vmdeploy
          deploymentMode: Incremental
          failOnStdErr: true     