# This is a basic workflow to help you get started with Actions

name: armDeployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  armDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Azure CLI ARM Deployment
        uses: Azure/cli@1.0.4
        with:
          inlinescript: |
            az deployment sub create --location "southeast asia" --template-file ./arm-templates/arm-resourcegroup.json
