# This is a basic workflow to help you get started with Actions

name: armDeployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  armDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: 43b3f2ee-7c26-4ac9-b907-0fd7ce508380
          region: southeast asia
          template: ./arm-templates/arm-resourcegroup.json
          deploymentName: arm-resourcegroup
          deploymentMode: Incremental
          failOnStdErr: true

      - name: Deploy Storage Account to resource group
        uses: Azure/arm-deploy@v1
        with:
          region: southeast asia
          resourceGroup: rg-armtemplate-github
          subscriptionId: 43b3f2ee-7c26-4ac9-b907-0fd7ce508380
          template: ./arm-templates/storageaccount.json
          parameters: ./arm-templates/storageaccount.parameters.json
          deploymentName: arm-storageaccount
          deploymentMode: Incremental
          failOnStdErr: true          